Submission by: James Della-Giustina

In [1]:
import numpy as np

In [37]:
def get_LU_Naive(a):
    k=len(a) # Number of columns/rows of the input matrix a
    print('k = ', k)
    L=np.eye(k, dtype=float) #Identity matrix of equal size of a
    U=a.copy() # Operate on U and keep a unchanged  
    print('a=\n',a)
    count=0 # Row counter to operate on 
    while count+1 < k: #count starts at 1 but is set to 0 since the rows are indexed starting at 0
        print('*** count = {} ****'.format(count))
        for i in range(1,k-count): # We want i to range over the number of rows that we want to eliminate, so its 'range' must decrease for each pivot column
            print('*** i = {} ***'.format(i))
            print('U[count+i,count] = ', U[count+i,count])
            if U[count+i,count]==0: # Handle the case for division by 0 by skipping the rows that already have zero below the pivot
                print('the if statement has been entered')
                i=i+1
            else: 
                coeff=U[count+i,count]/U[count,count] # Coefficent to negate the row below the pivot is that entry divided by the pivot
                L[count+i,count]=coeff   # Store into our lower triangular coefficient matrix L
                U[count+i,:]= -coeff*U[count,:]+U[count+i,:] # Perform the row operation to produce zeros below the pivot using the negative coeffecient
                print('coeff = ', coeff)
                print('U = \n\t', U)
                
        count=count+1
    print('U=\n',U)
    print('L=\n',L)
    return L, U

In [38]:
n = 3
a = np.arange(n**2).reshape((n,n)) + 1
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
ell, you = get_LU_Naive(a)

k =  3
a=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
*** count = 0 ****
*** i = 1 ***
U[count+i,count] =  4
coeff =  4.0
U = 
	 [[ 1  2  3]
 [ 0 -3 -6]
 [ 7  8  9]]
*** i = 2 ***
U[count+i,count] =  7
coeff =  7.0
U = 
	 [[  1   2   3]
 [  0  -3  -6]
 [  0  -6 -12]]
*** count = 1 ****
*** i = 1 ***
U[count+i,count] =  -6
coeff =  2.0
U = 
	 [[ 1  2  3]
 [ 0 -3 -6]
 [ 0  0  0]]
U=
 [[ 1  2  3]
 [ 0 -3 -6]
 [ 0  0  0]]
L=
 [[1. 0. 0.]
 [4. 1. 0.]
 [7. 2. 1.]]


In [40]:
ell

array([[1., 0., 0.],
       [4., 1., 0.],
       [7., 2., 1.]])

In [41]:
you

array([[ 1,  2,  3],
       [ 0, -3, -6],
       [ 0,  0,  0]])

In [42]:
ell@you - a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])