# Grade: 50/50

Submission by: James Della-Giustina, Craig Riley, Mitchell Macadams, Gavin Andrews

In [1]:
import numpy as np

In [2]:
def get_LU_Naive(a):
    k=len(a) # Number of columns/rows of the input matrix a
    L=np.eye(k, dtype=float) #Identity matrix of equal size of a
    U=a.copy() # Operate on U and keep a unchanged  
    print('a=\n',a)
    count=0 # Row counter to operate on 
    while count+1 < k: #count starts at 1 but is set to 0 since the rows are indexed starting at 0
        for i in range(1,k-count): # We want i to range over the number of rows that we want to eliminate, so its 'range' must decrease for each pivot column
            if U[count+i,count]==0: # Handle the case for division by 0 by skipping the rows that already have zero below the pivot
                i=i+1
            else: 
                coeff=U[count+i,count]/U[count,count] # Coefficent to negate the row below the pivot is that entry divided by the pivot
                L[count+i,count]=coeff   # Store into our lower triangular coefficient matrix L
                U[count+i,:]= -coeff*U[count,:]+U[count+i,:] # Perform the row operation to produce zeros below the pivot using the negative coeffecient
        count=count+1
    return L,U

# For grading purposes below
None of your group members are in MATH 535, so this is graded as a MATH 435 assignment

In [8]:
np.set_printoptions(precision = 2, suppress = True) # show fewer decimal places in outputs

In [3]:
def gen_mat(n, low = -3, high = 3, MATH535 = False):
    """
    Generate a random, invertible symmetric nxn matrix
    with integer entries and whose determinant is equal
    to +1 or 1. 
    """
    a = np.random.randint(low, high, size = (n, n))
    a = np.tril(a, -1) + np.eye(n) # np.tril grabs lower triangle
    a = a.T@a
    
    if MATH535 == True: 
        # randomly permute the rows and columns. 
        p_mat = np.eye(n)[:,np.random.permutation(n)]
        q_mat = np.eye(n)[:,np.random.permutation(n)]
        a = p_mat.T@a@q_mat
    return a

In [4]:
# generate a matrix
#
a = gen_mat(5)

In [9]:
# Run your code on the generated matrix: 
#
L, U = get_LU_Naive(a)

a=
 [[ 10.   2.  -5.   1.   0.]
 [  2.  10. -11.   6.   2.]
 [ -5. -11.  14.  -7.  -2.]
 [  1.   6.  -7.   5.   2.]
 [  0.   2.  -2.   2.   1.]]


In [10]:
# Check that L and U are lower and upper triangular respectively: 
#
L, U

(array([[ 1.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.2 ,  1.  ,  0.  ,  0.  ,  0.  ],
        [-0.5 , -1.04,  1.  ,  0.  ,  0.  ],
        [ 0.1 ,  0.6 , -0.42,  1.  ,  0.  ],
        [ 0.  ,  0.21,  0.08,  0.69,  1.  ]]),
 array([[ 10.  ,   2.  ,  -5.  ,   1.  ,   0.  ],
        [  0.  ,   9.6 , -10.  ,   5.8 ,   2.  ],
        [  0.  ,   0.  ,   1.08,  -0.46,   0.08],
        [  0.  ,   0.  ,   0.  ,   1.2 ,   0.83],
        [  0.  ,   0.  ,   0.  ,   0.  ,   0.01]]))

In [11]:
# Now check that A = LU: 
#
np.max(a - L@U) # should be zero (up to numerical error)

8.881784197001252e-16

In [12]:
# Nice work. 